spring.application.name=backend

spring.ai.model.chat=${SPRING_AI_MODEL_CHAT:google-genai}

spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}

spring.ai.google.genai.chat.options.model=${SPRING_AI_GOOGLE_GENAI_CHAT_OPTIONS_MODEL:gemini-2.5-flash}
